sudo: required
dist: xenial

branches:
  only:
  - master
  - /^v[0-9]/

env:
  global:
    - KUBEVIRT_VER=v0.8.0

jobs:
  include:
    - stage: Tests
      name: "minikube (1.11)"
      env: CPLATFORM=minikube CDIST=kubernetes CVER=1.11.3

    - name: "minikube (1.11) with quay.io/fabiand/virtbuilder image"
      env: CPLATFORM=minikube CDIST=kubernetes CVER=1.11.3 USE_QUAY=true

services:
  - docker

before_script:
## FIXME Workaround for https://github.com/kubernetes/kubernetes/issues/61058
### And https://github.com/LiliC/travis-minikube/blob/e0f26f7b388057f51a0e2558afd5f990e07b6c49/.travis.yml#L11
- sudo mount --make-rshared /

- bash -x ci/prepare-host $CPLATFORM $CVER
- bash -x ci/prepare-host oc 3.10.0
- bash -x ci/start-cluster $CPLATFORM $CVER
- bash -x ci/deploy-kubevirt $CDIST $KUBEVIRT_VER

script:
- bash -x test.sh
