apiVersion: v1
kind: Template
metadata:
  name: virtbuilder-job
  annotations:
    openshift.io/display-name: "Populate a PVC with a VM image"
    description: >-
      This template can be used to populate a PVC with a virt-builder image.
      Use `virt-builder --list` to get all available templates.
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/fabiand/virtbuilder"
    openshift.io/support-url: "https://github.com/fabiand/virtbuilder/issues"
    template.openshift.io/bindable: "false"
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: virtbuilder
    labels:
      app: virtbuilder
  spec:
    template:
      metadata:
        labels:
          app: virtbuilder
      spec:
        restartPolicy: OnFailure
        containers:
        - name: virtbuilder
          image: quay.io/fabiand/virtbuilder:latest
          args:
          - ${OSNAME}
          - ${DISKSIZE}
          env:
          - name: INSTALL
            value: cloud-init
          - name: RUN_COMMAND
            value: systemctl enable cloud-init cloud-config
          volumeMounts:
          - mountPath: "/pvc"
            name: target
          - mountPath: "/root/.cache/virt-builder/"
            name: cache
        volumes:
        - name: target
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        - name: cache
          persistentVolumeClaim:
            claimName: virtbuilder-cache
parameters:
- name: PVCNAME
  description: Name of the target PVC
  required: true
- name: OSNAME
  description: Name of the OS image to be written on the target PVC
  required: true
- name: DISKSIZE
  description: >
    Size of the final disk (must be larger than the template and smaller than
    the PVC)
