apiVersion: v1
kind: Template
metadata:
  name: virtbuilder-job
  annotations:
    openshift.io/display-name: "Red Hat Enterprise Linux 7.5 VM"
    description: >-
      This template can be used to create a VM suitable for
      Red Hat Enterprise Linux 7.5.
      The template assumes that a PVC is available which is providing the
      necessary RHEL disk image.
    tags: "kubevirt,virtualmachine,linux,rhel"
    iconClass: "icon-rhel"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/fabiand/common-templates"
    openshift.io/support-url: "https://github.com/fabiand/common-templates/issues"
    template.openshift.io/bindable: "false"
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: virtbuilder
    labels:
      app: virtbuilder
  spec:
    template:
      metadata:
        labels:
          app: virtbuilder
      spec:
        containers:
        - name: virtbuilder
          image: quay.io/fabiand/virtbuilder
          imagePullPolicy: IfNotPresent
          args:
          - ${OSNAME}
          - ${DISKSIZE}
          volumeMounts:
          - mountPath: "/pvc"
            name: target
          - mountPath: "/root/.cache/virt-builder/"
            name: cache
        volumes:
        - name: target
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        - name: cache
          persistentVolumeClaim:
            claimName: virtbuilder-cache
parameters:
- name: PVCNAME
  description: Name of the target PVC
  required: true
- name: OSNAME
  description: Name of the OS image to be written on the target PVC
  required: true
- name: DISKSIZE
  description: >
    Size of the final disk (must be larger than the template and smaller than
    the PVC)
