apiVersion: v1
kind: Template
metadata:
  name: pvc
  annotations:
    openshift.io/display-name: "Create a PVc of a given size"
    description: >-
      This template can be used to create a PVC fo a given size.
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/fabiand/virtbuilder"
    openshift.io/support-url: "https://github.com/fabiand/virtbuilder/issues"
    template.openshift.io/bindable: "false"
objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "${SIZE}"
parameters:
- name: NAME
  description: Name of the PVC
  required: true
- name: SIZE
  description: Size of the PVC
  required: true
